project:
  type: website
  output-dir: docs
  


website:
  navbar:
    logo: "tabs/tools/images/dataidlogo.png"
    left:
      - text: 'Home'
        href: index.qmd

      - text: 'Units'
        menu:
          - tabs/units/biosids/biosids.qmd

      - text: 'Training'
        menu:
          - tabs/units/radiant/radiant.qmd

# Right bar content
    right:
      - about.qmd
      - text: 'Blog'
        href: tabs/blog/blog.qmd
      - text: 'Tools'
        href: tabs/tools/tools.qmd

format: 
  html: 
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 300px
      gutter-width: 1.5rem
    theme: cosmo
    embed-resources: true
    self-contained: true
    page-layout: full
    fig-dpi: 300
    toc: true



